import { World } from "./World.js";
import { QUESTS, SIDE_STORIES, TASKS } from "./data.js";
import { AudioSystem } from "./Audio.js";
import { STANDARD_MAP, hasPublishableStandardMap } from "./mapPolicy.js";

const SAVE = "huaxia-artifact-journey-v1";

export class Game {
  constructor(){
    this.state={quest:0,boat:false,boatEver:false,done:false,discoveries:[]}; this.near=null; this.queue=[];this.recentConversation=null;this.mapTarget=null;this.audio=new AudioSystem();
    this.ui={timeline:document.querySelector("#timeline-screen"),map:document.querySelector("#map-screen"),world:document.querySelector("#world-screen"),ending:document.querySelector("#ending-screen"),questCard:document.querySelector("#quest-card"),questToggle:document.querySelector("#quest-toggle"),questCount:document.querySelector("#quest-count"),questTitle:document.querySelector("#quest-title"),questGoal:document.querySelector("#quest-goal"),questCopy:document.querySelector("#quest-copy"),questMemory:document.querySelector("#quest-memory"),memoryRoute:document.querySelector("#memory-route"),mapObjective:document.querySelector("#map-objective"),interaction:document.querySelector("#interaction"),inName:document.querySelector("#interaction-name"),action:document.querySelector("#interaction-action"),dialogue:document.querySelector("#dialogue"),speaker:document.querySelector("#dialogue-speaker"),text:document.querySelector("#dialogue-text"),toast:document.querySelector("#toast"),worldMap:document.querySelector("#world-map"),mapCanvas:document.querySelector("#mini-map-canvas"),lampStatus:document.querySelector("#lamp-status"),lampCard:document.querySelector("#lamp-card"),direction:document.querySelector("#camera-direction"),viewToggle:document.querySelector("#interior-toggle"),journal:document.querySelector("#journal"),journalCount:document.querySelector("#journal-count"),journalList:document.querySelector("#journal-list"),taskPanel:document.querySelector("#task-panel"),taskKicker:document.querySelector("#task-kicker"),taskTitle:document.querySelector("#task-title"),taskIntro:document.querySelector("#task-intro"),taskActions:document.querySelector("#task-actions"),taskFeedback:document.querySelector("#task-feedback"),taskCancel:document.querySelector("#task-cancel"),mapBase:document.querySelector("#official-map-base"),mapReview:document.querySelector("#map-review-copy"),mapApproval:document.querySelector("#map-approval")};
    this.world=new World(document.querySelector("#world"),{onNearChange:(o)=>this.setNear(o),onPosition:(p)=>this.updateDot(p),onMapReady:(data)=>{this.mapData={...this.mapData,...data};if(data.target)this.mapTarget=data.target;this.drawMiniMap()},onBlocked:(message)=>this.toast(message),onMoment:(message)=>this.toast(message),onDirection:(d)=>this.ui.direction.textContent=d,onInteriorChange:(inside)=>{this.ui.viewToggle.classList.toggle("is-active",inside);this.ui.viewToggle.textContent=inside?"屋内视角 · 开":"屋内视角"},onBoatChange:(boat)=>{this.state.boat=boat;this.save();if(!boat){this.ui.interaction.classList.add("is-hidden");this.toast("独木舟已经靠岸。")}}});
    this.bind(); this.load(); this.normalizeJourney(); this.refreshMap();
  }
  bind(){
    document.querySelector(".era-active").addEventListener("click",()=>{this.audio.click();this.show("map")});
    document.querySelector("[data-back]").addEventListener("click",()=>this.show("timeline"));
    document.querySelector("#liangzhu-marker").addEventListener("click",()=>this.startWorld());
    document.querySelector("#return-map").addEventListener("click",()=>this.show("map"));
    document.querySelector("#map-toggle").addEventListener("click",()=>this.ui.worldMap.classList.remove("is-hidden"));
    document.querySelector("#map-close").addEventListener("click",()=>this.ui.worldMap.classList.add("is-hidden"));
    document.querySelector("#journal-toggle").addEventListener("click",()=>{this.audio.click();this.renderJournal();this.ui.journal.classList.remove("is-hidden")});
    document.querySelector("#journal-close").addEventListener("click",()=>this.ui.journal.classList.add("is-hidden"));
    document.querySelector("#journey-reset").addEventListener("click",()=>this.resetJourney());
    this.ui.questToggle.addEventListener("click",()=>{this.audio.click();const expanded=this.ui.questCard.classList.toggle("is-expanded");this.ui.questToggle.textContent=expanded?"收起任务":"展开任务";this.ui.questToggle.setAttribute("aria-expanded",String(expanded));});
    document.querySelector("#camera-turn").addEventListener("click",()=>{this.audio.click();this.world.turnCamera()});
    this.ui.viewToggle.addEventListener("click",()=>{this.audio.click();this.world.toggleInteriorView()});
    this.ui.action.addEventListener("click",()=>this.activate());this.ui.taskCancel.addEventListener("click",()=>this.cancelTask());
    document.addEventListener("pointerup",()=>{if(!this.ui.dialogue.classList.contains("is-hidden"))this.closeDialogue();});
    addEventListener("keydown",e=>{if((e.key==="e"||e.key==="Enter")&&!this.ui.interaction.classList.contains("is-hidden"))this.activate();if((e.key===" "||e.key==="Enter"||e.key==="Escape")&&!this.ui.dialogue.classList.contains("is-hidden")){e.preventDefault();this.closeDialogue();}});
  }
  show(which){["timeline","map","world","ending"].forEach(k=>this.ui[k].classList.toggle("is-hidden",k!==which));if(which!=="world"){this.ui.worldMap.classList.add("is-hidden");this.ui.journal.classList.add("is-hidden");this.audio.stopAmbient()}if(which==="map")this.refreshMap();}
  normalizeJourney(){if(!Array.isArray(this.state.discoveries))this.state.discoveries=[];const q=Number(this.state.quest);if(Number.isInteger(q)&&q>=0&&q<QUESTS.length)return false;this.state.quest=0;this.state.boat=false;this.state.boatEver=false;this.save();return true;}
  resetJourney(){if(!confirm("要从玉料山重新开始玉琮王的旅程吗？当前任务进度与见闻簿将被清除。"))return;this.state={quest:0,boat:false,boatEver:false,done:false,discoveries:[]};this.activeTask=null;this.recentConversation=null;this.ui.taskPanel.classList.add("is-hidden");this.ui.dialogue.classList.add("is-hidden");this.save();this.refreshMap();this.world.build();this.startWorld();}
  startWorld(){const reset=this.normalizeJourney();this.show("world");this.audio.settlement();if(!this.world.started)this.world.build();this.state.boat=false;this.world.setBoat(false);this.updateQuest();this.renderJournal();if(reset)this.toast("上一轮旅程已结束；现在从玉料的山重新开始。");if(this.state.quest===0)this.say([["玉琮王", "我忘了自己的来时路。你可以自由探索这座城；若想替我找回记忆，就从西边的玉矿山开始。"]]);else{const q=QUESTS[this.state.quest];this.toast(`继续记忆：${q.title}。${q.hint}`)}}
  updateQuest(){const q=QUESTS[this.state.quest];if(!q)return;this.ui.questCount.textContent=`${String(this.state.quest+1).padStart(2,"0")} / 07`;this.ui.questTitle.textContent=q.title;this.ui.questGoal.textContent=`目标：${q.target} · ${q.hint}`;this.ui.questCopy.textContent=q.copy;this.ui.questMemory.textContent=q.memory;this.ui.mapObjective.textContent=`当前目标：${q.target}`;[...this.ui.memoryRoute.children].forEach((li,i)=>li.classList.toggle("is-current",i===q.chapter));this.world.setQuest(q.id);this.drawMiniMap();}
  setNear(o){const changed=o?.id!==this.near?.id;this.near=o;if(changed)this.recentConversation=null;if(!o||!this.ui.dialogue.classList.contains("is-hidden")||!this.ui.taskPanel.classList.contains("is-hidden")||this.recentConversation===o.id){this.ui.interaction.classList.add("is-hidden");return;}this.ui.inName.textContent=o.name;const q=QUESTS[this.state.quest];const isTaskTarget=o.id===q?.id;this.ui.action.textContent=o.kind==="boat"?(this.state.boat?"靠岸中":isTaskTarget?TASKS[q.id].action:"登船"):o.kind==="home"?o.action:o.kind==="task"?o.action:o.kind==="activity"?o.action:isTaskTarget?TASKS[q.id].action:o.kind==="quest"?"交谈":"听他说说";this.ui.interaction.classList.remove("is-hidden");}
  recordDiscovery(o){
    const id=o?.tree?"tree-fruit":o?.id;if(!id)return false;
    if(!this.state.discoveries.includes(id)){this.state.discoveries.push(id);this.save();this.renderJournal();return true}return false;
  }
  journalEntry(id){
    if(id==="tree-fruit")return{name:"树荫下的栎树",copy:"摇动枝叶后，果实落进湿草。树荫、果实和木材都是湿地聚落的日常资源。"};
    return SIDE_STORIES.find(item=>item.id===id)||this.world.interactables.find(item=>item.userData.id===id)?.userData;
  }
  renderJournal(){
    const records=this.state.discoveries.map(id=>({id,...this.journalEntry(id)})).filter(item=>item.name&&item.copy);this.ui.journalCount.textContent=records.length;this.ui.journalList.replaceChildren();
    if(!records.length){const empty=document.createElement("li");empty.className="journal-empty";empty.textContent="尚未记录。先去看看一棵树、一处水台，或一间高脚屋。";this.ui.journalList.append(empty);return}
    for(const item of records.slice().reverse()){const row=document.createElement("li"),name=document.createElement("b"),copy=document.createElement("span");name.textContent=item.name;copy.textContent=item.copy;row.append(name,copy);this.ui.journalList.append(row)}
  }
  talk(o,lines,done){this.recentConversation=o.id;this.say(lines,done)}
  startTask(q,o){this.activeTask={id:q.id,object:o};const task=TASKS[q.id];this.world.playMoment(q.id);if(task.mode==="sequence"){this.world.beginTaskStations(q.id,task.options);this.toast("任务开始：跟着浮光找到场景里的第一件工具。完成一步，下一件才会出现。");return;}this.ui.taskKicker.textContent=task.kicker;this.ui.taskTitle.textContent=task.title;this.ui.taskIntro.textContent=task.intro;this.ui.taskFeedback.textContent="";this.ui.taskActions.replaceChildren();this.ui.taskPanel.classList.remove("is-hidden");if(q.id==="quarry")this.renderMaterialTask(q,task);else this.renderSelectTask(q,task);}
  taskButton(label){const b=document.createElement("button");b.type="button";b.className="task-choice";b.textContent=label;this.ui.taskActions.append(b);return b}
  renderSequenceTask(q,task){let step=0;const glyphs={boat:["◒","⌇","➜"],transport:["⌁","◈","▰"],workshop:["╱","◌","⊙"],tomb:["◇","▱","⚑"],flood:["⌂","◉","✦"]}[q.id]||["①","②","③"];const buttons=task.options.map((item,index)=>{const b=this.taskButton(item.label);b.classList.add("task-gesture");b.innerHTML=`<span class="task-glyph" aria-hidden="true">${glyphs[index]}</span><span class="task-step">${item.label}</span><i>步骤 ${index+1}</i>`;b.addEventListener("click",()=>{if(!this.activeTask||this.activeTask.id!==q.id)return;if(index!==step){this.audio.error();step=0;buttons.forEach(x=>{x.disabled=false;x.classList.remove("is-done")});this.ui.taskFeedback.textContent="顺序不对，工具回到原位；看看场景里的动作提示后再试。";return;}this.audio.click();b.disabled=true;b.classList.add("is-done");step++;if(step===task.options.length)this.solveTask(q,task);else this.ui.taskFeedback.textContent=`动作完成。接着执行第 ${step+1} 步。`;});return b});this.ui.taskFeedback.textContent="按场景里的工作顺序，依次点选手边的工具与动作。";}
  renderSelectTask(q,task){const correct=task.options.filter(x=>x.correct).length;const chosen=new Set;task.options.forEach((item,index)=>{const b=this.taskButton(item.label);b.addEventListener("click",()=>{if(!this.activeTask||this.activeTask.id!==q.id||b.disabled)return;if(!item.correct){this.audio.error();b.classList.add("is-wrong");b.disabled=true;this.ui.taskFeedback.textContent="这不是要找的东西。看看材质和它将要承担的用途。";return;}this.audio.jade();chosen.add(index);b.disabled=true;b.classList.add("is-done");if(chosen.size===correct)this.solveTask(q,task);else this.ui.taskFeedback.textContent="找对了一件，再看看还有没有同样重要的物件。";});});this.ui.taskFeedback.textContent="仔细选择；选错不会扣进度。";}
  renderMaterialTask(q,task){
    // A genuine CSS 3D cube gives each material a top, front and side face.
    // Its pixel chips are deliberately different by material, like a block texture.
    const materials=["jade-ore","loose-earth","layered-slate"];
    const letters=["A","B","C"];const wrap=document.createElement("div");wrap.className="material-choices";
    task.options.forEach((item,index)=>{const b=document.createElement("button");b.type="button";b.className="material-choice";b.setAttribute("aria-label",`${letters[index]}：${item.label}`);b.innerHTML=`<span class="voxel-stage" aria-hidden="true"><span class="voxel-cube ${materials[index]}"><i class="voxel-face voxel-front"></i><i class="voxel-face voxel-right"></i><i class="voxel-face voxel-top"></i><i class="voxel-face voxel-back"></i><i class="voxel-face voxel-left"></i><i class="voxel-face voxel-bottom"></i></span></span><b>${letters[index]}</b>`;b.addEventListener("click",()=>{if(!this.activeTask||this.activeTask.id!==q.id||b.disabled)return;if(!item.correct){this.audio.error();b.disabled=true;b.classList.add("is-wrong");this.ui.taskFeedback.textContent="这块质地松散或层裂，磨制时会破。再观察石皮下的光泽与纹理。";return;}this.audio.jade();b.disabled=true;b.classList.add("is-done");this.solveTask(q,task);});wrap.append(b);});this.ui.taskActions.append(wrap);this.ui.taskFeedback.textContent="请选择适合制作玉琮的玉料。";
  }
  solveTask(q,task){if(!this.activeTask||this.activeTask.id!==q.id)return;this.audio.success();this.world.clearTaskStations();this.activeTask=null;this.ui.taskPanel.classList.add("is-hidden");const advanced=this.completeQuest(q.id);this.recentConversation=null;if(advanced&&!this.state.done){const fact=q.fact?` 考古线索：${q.fact}`:"";this.say([[q.speaker,`${task.success} ${q.line}${fact}`]]);}}
  cancelTask(){if(!this.activeTask)return;this.world.clearTaskStations();this.activeTask=null;this.ui.taskPanel.classList.add("is-hidden");this.ui.taskFeedback.textContent="";this.setNear(this.near);}
  activate(){const o=this.near;if(!o)return;this.ui.interaction.classList.add("is-hidden");if(o.kind==="task"){const task=TASKS[o.taskId];if(!this.activeTask||this.activeTask.id!==o.taskId||!task)return;const result=this.world.completeTaskStation(o.taskId,o.step);if(result==="wrong"){this.audio.error();this.toast("这一步还太早。看看场景里哪件物品应当先被处理。");this.setNear(o);return}this.audio.click();if(result)this.solveTask({id:o.taskId},task);else this.toast("操作完成。场景中的其余物件仍可自由查看，下一步已经亮起。");return;}if(o.kind==="home"){this.world.routeIntoHouse(o.home);return;}if(this.activeTask)return;let q=QUESTS[this.state.quest];if(!q){this.normalizeJourney();this.updateQuest();q=QUESTS[this.state.quest];this.toast("记忆进度已恢复到第一段，请重新与采玉人交谈。");this.setNear(this.near);return;}if(o.kind==="activity"){const fresh=this.recordDiscovery(o);this.audio.daily(o.id);this.toast(`${this.world.doActivity(o.id)}${fresh?" 见闻簿 +1":""}`);return;}if(o.kind==="boat"&&q.id==="boat"){this.startTask(q,o);return;}if(o.kind==="boat"){if(this.state.boat){this.toast("靠近码头会自动下船，不需要再点借船。");return;}if(this.state.quest<2){this.toast("先从采玉人那里完成辨玉任务，再来找船娘。");return;}this.state.boat=true;this.state.boatEver=true;this.world.setBoat(true);this.toast("你坐上独木舟。沿河行进，靠近码头会自动下船。");this.save();return;}
    if(o.kind==="side"){const story=SIDE_STORIES.find(x=>x.id===o.id);this.recordDiscovery(o);this.talk(o,[[story.name,story.copy]]);return;}
    if(o.id!==q.id){this.talk(o,[[o.name,o.copy]]);return;}
    if(q.id==="transport"&&!this.state.boatEver){this.toast("河道挡住了去路。先在西南码头借船并登船。");return;}
    this.startTask(q,o);
  }
  completeQuest(expectedId=null){const completed=QUESTS[this.state.quest];if(!completed||this.completing||(expectedId&&completed.id!==expectedId))return false;this.completing=true;this.state.quest++;if(this.state.quest>=QUESTS.length){this.state.done=true;this.save();this.world.collapse();this.refreshMap();this.show("ending");this.completing=false;return true;}this.updateQuest();this.save();this.toast(`任务完成：${completed.title}。下一步：${QUESTS[this.state.quest].target}`);this.completing=false;return true;}
  say(lines,done=null){const line=lines.at(-1);if(!line)return;this.after=done;this.ui.speaker.textContent=line[0];this.ui.text.textContent=line[1];this.ui.dialogue.classList.remove("is-hidden");}
  closeDialogue(){if(this.ui.dialogue.classList.contains("is-hidden"))return;this.ui.dialogue.classList.add("is-hidden");const f=this.after;this.after=null;if(f)f();else this.setNear(this.near);}
  updateDot(p){this.lastPosition={x:p.x,z:p.z};this.drawMiniMap();}
  drawMiniMap(){
    const canvas=this.ui.mapCanvas,data=this.mapData,p=this.lastPosition;if(!canvas||!data)return;const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,minX=-64,maxX=64,minZ=-40,maxZ=40,toX=x=>(x-minX)/(maxX-minX)*w,toY=z=>(z-minZ)/(maxZ-minZ)*h;
    const polygon=(pts,fill,stroke)=>{ctx.beginPath();pts.forEach(([x,z],i)=>i?ctx.lineTo(toX(x),toY(z)):ctx.moveTo(toX(x),toY(z)));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}};
    ctx.clearRect(0,0,w,h);ctx.fillStyle="#215a70";ctx.fillRect(0,0,w,h);polygon(data.land,"#6f8e67","#c2aa76");data.water.forEach(poly=>polygon(poly,"#4d9eb5"));
    // Docks are supporting navigation, not quests: keep them quiet so the
    // current orange exclamation remains the one clear destination on the map.
    ctx.fillStyle="#c7c3a2";data.docks.forEach(d=>ctx.fillRect(toX(d.x)-1.5,toY(d.z)-1.5,3,3));
    const target=data.target||this.mapTarget;if(target){const pulse=6+Math.sin(performance.now()/230)*1.5,tx=toX(target.x),ty=toY(target.z);ctx.strokeStyle="#fff0a5";ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(tx,ty,pulse,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#ef783d";ctx.beginPath();ctx.arc(tx,ty,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#172e26";ctx.font="bold 14px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("!",tx,ty+.4);ctx.fillStyle="#fff0bd";ctx.font="bold 10px sans-serif";ctx.fillText("当前任务",tx,ty-11)}
    if(p){ctx.beginPath();ctx.arc(toX(p.x),toY(p.z),4.3,0,Math.PI*2);ctx.fillStyle="#fff3a8";ctx.fill();ctx.strokeStyle="#274438";ctx.lineWidth=1.5;ctx.stroke()}
  }
  toast(s){this.ui.toast.textContent=s;this.ui.toast.classList.remove("is-hidden");clearTimeout(this.timer);this.timer=setTimeout(()=>this.ui.toast.classList.add("is-hidden"),2600);}
  refreshMap(){this.ui.lampStatus.textContent=this.state.done?"西汉 · 已解锁（下一世界）":"西汉 · 待解锁";this.ui.lampCard.classList.toggle("unlocked",this.state.done);const ready=hasPublishableStandardMap();this.ui.mapBase.classList.toggle("is-approved",ready);this.ui.mapBase.style.backgroundImage=ready?`url(${STANDARD_MAP.assetUrl})`:"";this.ui.mapReview.textContent=ready?"正式底图已加载；文物标记以独立图层叠加。":"尚未载入带审图号且已完成公开使用审核的正式底图。";this.ui.mapApproval.textContent=ready?`审图号：${STANDARD_MAP.approvalNo}`:`待补：${STANDARD_MAP.catalogHint}`;}
  save(){localStorage.setItem(SAVE,JSON.stringify(this.state));} load(){try{this.state={...this.state,...JSON.parse(localStorage.getItem(SAVE)||"{}")} }catch(_){}this.state.boat=false;}
}
