import { QUESTS, SIDE_STORIES, TASKS } from "../src/game/data.js";
import { readFileSync } from "node:fs";

const assert=(ok,label)=>{if(!ok)throw new Error(`内容验收失败：${label}`);console.log(`✓ ${label}`)};
const route=["quarry","boat","transport","workshop","ritual","tomb","flood"];
assert(QUESTS.length===7,"玉琮王有完整的七段来时路");
assert(QUESTS.map(q=>q.id).join(",")===route.join(","),"主线按采料、借舟、运料、制玉、祭祀、入葬、覆灭排列");
assert(QUESTS.every(q=>q.title&&q.copy&&q.speaker&&q.line),"每一段都有任务文字与区域角色回应");
assert(QUESTS.every(q=>TASKS[q.id]?.options?.length>=3)&&Object.keys(TASKS).length===QUESTS.length,"七段主线均有可完成的场景任务，而非只靠交谈推进");
const taskTargets=["quarry","boat","transport","workshop","ritual","tomb","flood"];
assert(QUESTS.find(q=>q.id==="boat")?.line.includes("河就是边界"),"水路被设计为需要借船的可玩边界");
assert(!QUESTS.some(q=>q.copy.includes("土路")||q.hint.includes("土路")),"主线文本不再要求寻找已移除的道路");
assert(QUESTS.find(q=>q.id==="flood")?.line.includes("五千年后"),"结局包含文明覆灭与文物留存");
assert(SIDE_STORIES.length>=5,"开放世界包含不推进主线的日常人物");
const html=readFileSync(new URL("../index.html",import.meta.url),"utf8");
const markup=html+readFileSync(new URL("../src/styles.css",import.meta.url),"utf8");
const world=readFileSync(new URL("../src/game/World.js",import.meta.url),"utf8");
const game=readFileSync(new URL("../src/game/Game.js",import.meta.url),"utf8");
const mapCompliance=readFileSync(new URL("../docs/MAP_COMPLIANCE.md",import.meta.url),"utf8");
assert(game.includes("renderMaterialTask(q,task)")&&game.includes('const letters=["A","B","C"]')&&game.includes("voxel-stage")&&game.includes("voxel-cube")&&markup.includes(".voxel-front")&&markup.includes(".voxel-right")&&markup.includes(".voxel-top")&&markup.includes(".voxel-back")&&markup.includes("rotateY(-42deg)"),"采玉任务以六面实体方块呈现，并稳定露出顶面、正面和右侧面，而非纯文字按钮");
assert(!/良渚文化[0-9]*\.png/.test(markup),"良渚参考图未被直接放入游戏画面");
assert(world.includes("pointerMove")&&world.includes("turnCamera"),"开放世界支持拖动与东南西北镜头转向");
assert(markup.includes('id="mini-map-canvas"')&&world.includes("onMapReady")&&game.includes("drawMiniMap"),"全局地图由真实陆地、河网和码头坐标绘制");
assert(markup.includes('data-map-review="official-standard-map-required"')&&mapCompliance.includes("approval_no")&&mapCompliance.includes("asset_sha256")&&mapCompliance.includes("review_record"),"时代地图在接入官方底图前保留审图号、原始文件与审核记录发布闸门");
assert(world.includes("landPolygon")&&world.includes("buildOuterRiver"),"世界边界采用不规则陆地与外围大河");
assert(world.includes("]],9.0)")&&world.includes("dockBoatByCrossing={}")&&world.includes('id:"west-north"')&&world.includes('id:"west-south"'),"主河加宽且每条渡口水道复用一艘可见独木舟");
assert(world.includes("A landing is a small piece of water infrastructure")&&world.includes("const bollard=this.mesh")&&world.includes("const coil=new THREE.Mesh")&&world.includes('this.mat(C.wood,{texture:"wood"})'),"码头与独木舟具备木桩、系缆、踏板和绑扎细节，水路是可感知的生活空间");
assert(world.includes("buildTerrainScreens")&&world.includes("Layered groves")&&world.includes("eastern dike"),"树林、低丘与堤岸把大地图划分为有遮挡的探索片区");
assert(!html.includes('data-move="up"')&&world.includes('this.keys.has("w")')&&world.includes("pointerUp(e)"),"移除屏幕方向盘后仍保留键盘和点地移动");
assert(!markup.includes('id="camera-reset"')&&world.includes("pointerMove")&&world.includes("this.yaw-=dx*.009")&&!world.includes("safeCameraYaw"),"镜头可自由拖至任意角度，保留正北西南东的罗盘按钮但移除无用回家按钮");
assert(world.includes("buildSky")&&world.includes("foam(x,z,s=1)")&&!world.includes("BoxGeometry(1.8,.035,.05)"),"天空、浪花替代了白色横杆动画");
assert(world.includes("paddy(x,z,w,d)")&&world.includes("田埂")&&world.includes("0x789b85")&&world.includes("farm district has its own lanes"),"稻田包含田埂、浅水和成行稻株，并独立于道路布置");
assert(world.includes("eastern plot met the wetland edge")&&world.includes("[-14,10.5,3.9,2.9],[-8.2,10.5,3.7,2.9],[-14,15,4.1,3.0]")&&!world.includes("[-8.1,15,3.8,3.0]"),"冲突水田已删除，只保留三块干燥且分开的田");
assert(world.includes('this.makeNPC("rice"')&&world.includes('",-14,10.5,0xc9ad5a'),"阿禾位于现有稻田中，而非已移除的旧农田坐标");
assert(world.includes("elevatedAreas")&&world.includes("floorY")&&world.includes("buildFarDistricts"),"高脚民居有上下层探索与扩展聚落");
assert(!world.includes("bridge(")&&!world.includes("修桥"),"河道没有桥，渡河依赖独木舟与码头");
assert(world.includes("[[-47,28]")&&world.includes("[[12,-32]")&&world.includes("]],4.7)")&&world.includes("]],4.65)")&&world.includes("]],4.55)")&&world.includes("]],4.6)"),"五条宽阔河道连通成网，而非一条孤立窄支流");
assert(world.includes('keeper:"boat-ritual-south"')&&world.includes('keeper:"boat-west-south"')&&world.includes('keeper:"boat-workshop-south"')&&world.includes("this.docks.forEach(d=>this.makeNPC(d.keeper"),"每一保留码头都有船夫，祭台与主要水道两岸可返航");
assert(world.includes("wallColliders")&&world.includes("groundColliders")&&world.includes("blockedByWall")&&world.includes("ramps.push"),"高脚屋具备墙体碰撞与阶梯移动表面");
assert(world.includes("blockReason")&&world.includes("高脚屋的入口在正面")&&world.includes("this.route=["),"建筑碰撞不会误报河水，点屋内会自动规划木梯入口");
assert(world.includes("navigationMeshes")&&world.includes("intersectObjects(this.navigationMeshes")&&world.includes("routeIntoHouse"),"点击立体高脚屋会命中房屋本体，不会落到屋后的世界边界");
assert(world.includes("routeOutOfHouse")&&world.includes("沿正面的木梯下楼"),"高脚屋上下楼均有自动木梯路线");
assert(world.includes("boxObstacleAt")&&world.includes("circleObstacleAt")&&world.includes("xOnly&&zOnly"),"角色按实体碰撞盒移动，遇到建筑与山石会沿边缘滑动而非卡死");
assert(world.includes("nav.userData.goTo")&&world.includes("houseHit?.object.userData.goTo"),"点击采玉人等角色会命中角色本体并前往其位置");
assert(world.includes("createMomentActors")&&world.includes("this.cinema")&&game.includes("playMoment(q.id)")&&world.includes("送葬队正在前往反山王陵"),"主线节点会触发可见场景、镜头聚焦与送葬队");
assert(world.includes('keeper:"boat-east"')&&world.includes('keeper:"boat-tomb"')&&game.includes('o.id==="boat"'),"反山王陵路线在东渡口提供可重复上船点");
assert(world.includes("scale.setScalar(.72)")&&world.includes("Same body scale as villagers"),"玩家阿玉与村民保持同尺度");
assert(world.includes('this.makeNPC("family"')&&world.includes("family.position.y=2.58")&&world.includes('this.discovery("loom"')&&world.includes(",-22.35,-16.92,2.58"),"屋内人物与物件位于放大的高脚屋楼板上");
assert(world.includes("this.outerWater.rotation.x=-Math.PI/2")&&world.includes("horizontal world surface")&&!world.includes("this.mesh(new THREE.PlaneGeometry(164,116),C.deepWater,0,-.42,0);this.island"),"外围水面保持水平，镜头转向不会被竖直蓝幕遮挡");
assert(world.includes("buildRitualPlatform(38,18)")&&world.includes("this.ritualEntry")&&world.includes("祭司在祭台上"),"祭台有独立台阶入口，点击祭司或台面均按台阶登台");
assert(world.includes("priest.position.y=1.075")&&world.includes("this.momentFigure(\"ritual\"")&&world.includes("null,null,1.075"),"祭司与祭仪人物位于祭台台面，不会嵌入底座");
assert(world.includes('id:"east-main-north",crossing:"tomb-main",x:25')&&world.includes('id:"east-main-south",crossing:"tomb-main",x:25')&&world.includes('keeper:"boat-east"'),"东渡口两岸都有停靠点，船夫与祭台不再重叠");
assert(world.includes("jade eye plaques")&&world.includes("jadeCong(x,y,z,scale=1)")&&world.includes("外方、内圆")&&world.includes("for(const dx of[-1.35,1.35])"),"祭台包含方圆玉琮、供案、火盆、旗幡与纹样层次");
assert(world.includes('this.makeNPC("quarry"')&&world.includes(',-39.5,14.2')&&world.includes("26,8")&&world.includes("38,18")&&world.includes("30,-18")&&world.includes("51,6"),"矿区、工坊、祭台、王陵与东堤分布在不同探索区，而非同一屏幕");
assert(taskTargets.filter(id=>id!=="boat").every(id=>world.includes(`makeNPC("${id}"`)||world.includes(`landmark("${id}"`))&&world.includes('keeper:"boat"'),"七个主线任务都有可命中的人物或场景目标");
assert(world.includes("[-31,-16,1.58]")&&world.includes("[-22,-17,1.62]")&&world.includes("larger homes occupy separate family plots")&&world.includes("seedClearings")&&!world.includes("[-16,-8.7,1]"),"所有聚落按统一留白规划，住宅更大且入口远离河岸");
assert(world.includes("small herd")&&world.includes("[-.26,-.12,.92")&&world.includes(".54,0xe0b69f"),"每座高脚屋下有成年猪和猪仔组成的小群养殖");
assert(world.includes("this.animals=[]")&&world.includes("updateAnimals(time)")&&world.includes("Livestock follows small closed foraging loops")&&world.includes("anchor:{x:pigX,z:pigZ}")&&world.includes('kind:"fowl"'),"猪群与家禽均在各自生活区内觅食移动，而非原地摆动");
assert(world.includes("Math.atan2(next.x-from.x,next.z-from.z)+Math.PI")&&world.includes("userData.facing"),"阿玉按移动方向转向，身体正面而不是背包朝向目的地");
assert(world.includes("const faceBridge")&&world.includes("complexion={quarry")&&world.includes("addRoleDetails(g,id,color)")&&world.includes("Math.atan2(next.x-from.x,next.z-from.z)+Math.PI"),"阿玉与村民具备克制的面部层次、肤色差异和职业细节，身体仍按点击移动方向转向");
assert(world.includes('this.mat(color,{texture:"weave"})')&&world.includes("const yoke=new THREE.Mesh")&&world.includes("const pendant=new THREE.Mesh")&&world.includes("const cuff=new THREE.Mesh")&&world.includes('plaque=add(new THREE.BoxGeometry(.16,.24,.045),C.jade'),"玩家和村民的衣物有纺织纹理、衣缘与克制的玉饰，不再只是单色人体几何体");
assert(world.includes("safeSpawn(-12.8,5.1)")&&world.includes("!this.isWater(x,z)")&&world.includes("West channel remains in the northern wetland"),"出生点保底落在陆地，西汊不切入出生庭院、农田或采玉道路");
assert(world.includes('this.makeNPC("quarry"')&&world.includes("this.mountain(-43,17.4")&&world.includes("quarryCamp(-39.5,14.2)"),"采玉人和营地位于矿山脚下的可走区域，不嵌进山体碰撞范围");
assert(!world.slice(world.indexOf("buildSettlement()"),world.indexOf("buildWorkshopDetails")).includes("this.trail(")&&!world.slice(world.indexOf("buildFarDistricts()"),world.indexOf("raisedGranary")).includes("this.trail("),"聚落与远区不再生成会误入河道的可见道路表面");
assert(!world.includes("trail(points")&&!world.includes("roadSegments"),"道路生成器及其旧留白规则已从世界代码移除");
assert(world.includes('texture(kind)')&&world.includes('kind==="water"')&&world.includes('kind==="waterNormal"')&&world.includes('normalTexture:"waterNormal"')&&world.includes('kind==="weave"')&&world.includes('texture:"thatch"'),"水面、夯土、木材、编织墙与茅草屋顶使用各自的程序纹理；河网与水田还具备独立法线波纹");
assert(world.includes('kind==="clay"')&&world.includes('kilnX,.14,kilnZ,{texture:"clay"}')&&world.includes('0xb87852,kilnX+dx,s*.86,kilnZ+dz,{texture:"clay"}')&&world.includes('this.mat(color,{texture:"clay"})'),"陶窑、陶罐与日常储物器使用具有火候与手作痕迹的独立陶土材质");
assert(world.includes("part=(geo,tint,px,py,pz,sx,sy,sz,rot=0,opt={})")&&world.includes('r*.61,.38,{texture:"stone"}')&&world.includes('buildShore(){')&&world.includes('C.stone,x,.13,z,{texture:"stone"}'),"山体裸岩、河岸砾石与散布巨石共享石纹材质，地貌不再由纯色几何体构成");
assert(world.includes("buildDailyLife()")&&world.includes("buildWaterTraffic()")&&world.includes("updateAmbientBoats")&&world.includes("buildWorkshopDetails"),"聚落包含日常器具、动态独木舟和可辨识的制玉工坊细节");
assert(world.includes("buildCourtyardDetails()")&&world.includes("Open ground in a settlement is not a drawn road")&&world.includes("Spawn courtyard"),"开局与农田边缘用院落生活细节填充，不以新的道路表面替代草地");
assert(world.includes("this.validateTransitNetwork()")&&world.includes("waterRouteIsSafe(route)")&&world.includes("环境独木舟路线离开了河道"),"停靠点与环境独木舟在进入世界时均经过真实水域校验");
assert(world.includes("const keepers=new Set((this.villagers||[]).map(v=>v.id))")&&world.includes("!keepers.has(d.keeper)"),"每一个保留渡口会校验对应船夫 NPC 已实际生成在世界中");
assert(world.includes("this.started=false;this.player=null")&&world.includes("this.resize();this.started=true"),"世界只在完整构建出玩家与可走场景后才开始渲染和响应操作");
assert(world.includes("cinematic?4.6:6.7"),"默认镜头保持平视斜角，人物、屋舍与水面有自然的近景尺度");
assert(world.includes("camera is an observer on dry ground")&&world.includes("this.onLand(cx,cz)&&!this.isWater(cx,cz)"),"镜头转向时自动避开河道，不会以大面积水面遮挡世界");
assert(world.includes("raisedGranary(34,25)")&&world.includes("晒—藏—防潮")&&world.includes('this.discovery("granary-store"')&&SIDE_STORIES.some(s=>s.id==="granary-store"),"支聚落存在可探索的高仓，将稻作储藏、防潮建筑与城市公共生活连接起来");
assert(world.includes("buildWaterworks()")&&world.includes("东侧堤坝露出夯土层、木桩和编束护坡"),"东侧堤坝呈现夯土、木桩与护坡的水利工程层次");
assert(world.includes('kind==="jade"')&&world.includes('kind==="stone"')&&world.includes('texture:"jade"')&&world.includes("玉的沁色、石纹和矿物斑点")&&world.includes('C.jade,x+dx,.19,z+dz,{texture:"jade"'),"玉琮与玉胚使用独立的沁色石纹材质，而非单一绿色方块");
assert(world.includes("Sluice boards, a gauge")&&world.includes("const gx=52.95,gz=6.0"),"东堤具有可辨认的闸板与水尺，呈现日常维护的水利节点");
assert(world.includes("const dryingMat")&&world.includes("const mill=")&&world.includes("const hearth=")&&world.includes("不侵占道路和任务路线"),"聚落院落补足晒谷、石磨与火塘等不阻断通行的生活生产痕迹");
assert(world.includes("this.solidCircles.push({x,z,r:.53})")&&world.includes("Small waterfowl provide")&&world.includes("if(f.duck)"),"东堤具有实体边界，河网中有持续游动的水禽作为尺度与生态细节");
assert(world.includes("this.solidCircles=[]")&&world.includes("buildCraftScenes()")&&world.includes("Separate work scenes")&&world.includes("const net=(x,z)"),"重置不累积地形碰撞，陶窑、渔网与织麻架构成可辨识的生产场景");
assert(game.includes("questToggle")&&markup.includes('id="quest-toggle"')&&markup.includes("展开任务"),"任务信息默认折叠为摘要，需要时再展开，不遮挡探索视野");
assert(game.includes('import { AudioSystem }')&&game.includes('this.audio.settlement()')&&game.includes('this.audio.success()')&&game.includes('this.audio.stopAmbient()')&&readFileSync(new URL("../src/game/Audio.js",import.meta.url),"utf8").includes("settlement()"),"河网、水鸟与火塘环境声及任务成败反馈在首次进入世界后接入，并在离开世界时停止");
assert(markup.includes('id="quest-goal"')&&game.includes("this.ui.questGoal.textContent")&&game.includes("目标：${q.target}"),"任务卡默认展示当前目标与提示，玩家无需展开也知道下一步");
assert(markup.includes('class="memory-evidence"')&&markup.includes("山与玉")&&markup.includes("稻与水")&&markup.includes("工与礼")&&markup.includes("墓与今"),"通关页以材料、水利、礼仪与墓葬的证据链回望整座良渚城");
assert(markup.includes('id="task-panel"')&&game.includes("startTask(q,o)")&&game.includes("solveTask(q,task)")&&game.includes("cancelTask()")&&game.includes("expectedId&&completed.id!==expectedId"),"主线任务可反复开启、完成后才推进，退出不会造成卡关");
assert(markup.includes('id="journey-reset"')&&game.includes("resetJourney()")&&game.includes("this.world.build();this.startWorld()"),"右上角提供带确认的进度重置，并从玉料山重新开局");
assert(game.includes("if(this.state.quest===0)this.say")&&game.includes("继续记忆：${q.title}"),"续玩时只提示当前记忆章节，不会错误重复玉料山开场台词");
assert(!markup.includes('class="player-status"')&&!markup.includes('class="move-pad"')&&!markup.includes('class="world-help"')&&markup.includes('class="hud-actions"'),"世界 HUD 移除冗余角色与方向提示，仅保留右上角核心操作");
assert(game.includes("normalizeJourney()")&&game.includes("Number.isInteger(q)")&&game.includes("记忆进度已恢复到第一段"),"旧版异常或已结束存档进入世界时会安全重置，不会因空任务对象崩溃");
assert(game.includes('ctx.fillRect(toX(d.x)-1.5')&&markup.includes("浅色方点为码头"),"地图将码头弱化为辅助方点，任务感叹号保持唯一醒目目标");
assert(game.includes("this.mapTarget")&&game.includes("当前任务")&&game.includes("data.target||this.mapTarget"),"地图持久绘制清晰的当前任务感叹号与文字标记");
assert(world.includes("g.add(this.label(name,1.86")&&world.includes("const marker=this.questMarker(2.35)"),"每位可交谈角色头顶显示身份，任务感叹号置于姓名上方");
assert(!world.includes("this.trail([[-39.5,14.2],[-47,14],[-52,11]]")&&!world.includes("reserveRoad([[-39.5,14.2],[-47,14],[-52,11]]"),"道路不会再贯穿或终止在民居里");
assert(game.includes("recentConversation")&&game.includes("talk(o,lines,done)")&&game.includes("this.recentConversation===o.id")&&!markup.includes('id="interaction-copy"')&&!markup.includes('id="dialogue-next"')&&game.includes("document.addEventListener(\"pointerup\"")&&game.includes("closeDialogue()"),"靠近角色只出现行动入口；独立对话可点击任意位置收起，不再重复文字或要求点关闭");
assert(world.includes("disembarkUntil")&&world.includes("o.userData.kind===\"boat\"")&&game.includes("靠近码头会自动下船"),"靠岸自动下船并短暂屏蔽借船交互，不会误触上船提示");
assert(world.includes("setPixelRatio(Math.min(devicePixelRatio,1.25))")&&world.includes("shadowMap.autoUpdate=false")&&world.includes("for(let i=0;i<170")&&world.includes("for(let i=0;i<35"),"降低渲染分辨率、静态阴影更新与环境网格数量以提升帧率");
assert(world.includes("if(!this.waterRouteIsSafe(route))throw new Error")&&world.includes("surveyed river-centre lines")&&!world.includes("safeRoute=route.filter"),"环境独木舟只沿已验证水域的河道中心线航行");
assert(world.includes("buildPalaceCompound")&&world.includes("buildNecropolis")&&world.includes("buildRiceProcessing")&&world.includes("buildFoodProcessing"),"高台居所、墓地、晒谷场与食物棚是独立的探索区域");
assert(world.includes("const graves=[[-3.65,1.75")&&world.includes("if(r>.9){const offering"),"反山墓地由多座不同规格墓丘及随葬陶器构成，而非孤立守卫与单一土丘");
assert(world.includes("The enclosure has a real gate gap")&&world.includes("this.solidCircles.push({x:x+dx,z:z+dz,r:r*.72})"),"宫殿围栏保留入口，墓丘具备实体边界");
assert(["palace","necropolis","rice-yard","food-yard"].every(id=>SIDE_STORIES.some(s=>s.id===id)),"新增区域都有可阅读的生活叙事");
assert(SIDE_STORIES.some(s=>s.id==="palace-resident")&&world.includes('"palace-resident","高台居所的执事"'),"高台居所拥有可交谈的执事，不再只是空建筑");
assert(["palace","palace-resident","rice-yard","food-yard","necropolis"].every(id=>world.includes(`"${id}"`))&&world.includes('villager.id==="palace-resident"?.14')&&world.includes('boatman=villager.id.startsWith("boat")'),"高台居所执事与远区工作者只在院落内小范围走位，船夫则继续守在码头");
assert(world.includes("gableRoof(x,y,z,w,d,h,roofTint=C.roof)")&&world.includes("complete 人字形 roof")&&world.includes("w=3.18*s,d=2.52*s")&&world.includes("wallTint=[0xa77f58,0xb18b60,0x9b7654]"),"民居扩大并改为完整人字形茅草屋顶，编墙与茅草有家庭差异");
assert(world.includes("this.gableRoof(x,floorY+.92,z,w*1.18,d*1.22,.54)")&&!world.includes("const roofA=this.mesh"),"高仓也使用完整人字形屋顶，不再保留两片分离的 V 字屋面");
assert(world.includes("this.shrub(")&&world.includes(".82+Math.random()*1.02")&&world.includes("Workers make short, role-shaped loops"),"树林比例、草丛层次与居民活动均得到增强");
assert(world.includes('type:"quarry"')&&world.includes('type:"grind"')&&world.includes('type:"cast"')&&world.includes("motion.tools[0].rotation"),"采玉、制玉、捕鱼等角色的工具动作与走位同步呈现");
console.log("开放世界主线与探索内容结构有效。");
