/*
 * 固定题面的可解性验收。每项都继续枚举到第二个解或穷尽，防止把
 * “看起来像谜题”的无解/多解状态混进游戏。
 */
const assert=(ok,label)=>{if(!ok)throw new Error(`谜题验收失败：${label}`);console.log(`✓ ${label}`)};

// Simon Tatham Net: 5x5:1319827eb3e918b6ae4b1a326（转为项目 N/E/S/W 位序）
{const n=5,a=[2,3,2,6,4,1,11,13,7,3,13,6,2,4,7,9,5,13,8,7,2,5,3,1,9],rot=m=>((m<<1)&15)|(m>>3),opts=a.map(m=>{const r=[m];for(let i=0;i<3;i++){m=rot(m);if(!r.includes(m))r.push(m)}return r}),out=[],now=Array(25),D=[[0,-1,1,4],[1,0,2,8],[0,1,4,1],[-1,0,8,2]];function f(i){if(out.length>1)return;if(i===25){const seen=new Set([12]),q=[12];while(q.length){const k=q.pop(),x=k%n,y=~~(k/n);for(const[dx,dy,b,z]of D){const xx=x+dx,yy=y+dy,j=yy*n+xx;if(xx>=0&&xx<n&&yy>=0&&yy<n&&(now[k]&b)&&(now[j]&z)&&!seen.has(j)){seen.add(j);q.push(j)}}}if(seen.size===25)out.push(1);return}const x=i%n,y=~~(i/n);for(const m of opts[i]){if((y===0&&(m&1))||(x===0&&(m&8))||(x===4&&(m&2))||(y===4&&(m&4)))continue;if(x&&!!(m&8)!==!!(now[i-1]&2))continue;if(y&&!!(m&1)!==!!(now[i-5]&4))continue;now[i]=m;f(i+1)}}f(0);assert(out.length===1,"水闸 Net：唯一解")}

// 公开 7x7 Hashiwokakero 小题面；交叉的 d-j / g-h 同时存在时无效。
{const nodes={a:2,b:2,c:1,d:1,e:4,f:3,g:3,h:2,i:4,j:3,k:2,l:3,m:1,n:3,o:4,p:2},edges=['ab','bc','ag','de','ef','ei','fl','gh','gm','hk','dj','jk','jn','io','lp','no','op'],ans=[];function f(i,cs,deg){if(ans.length>1)return;if(i===edges.length){if(cs[7]&&cs[10])return;if(Object.entries(nodes).some(([k,v])=>deg[k]!==v))return;const seen=new Set(['a']),q=['a'];while(q.length){const k=q.pop();edges.forEach((e,j)=>{if(cs[j]&&e.includes(k)){const other=e[0]===k?e[1]:e[0];if(!seen.has(other)){seen.add(other);q.push(other)}}})}if(seen.size===Object.keys(nodes).length)ans.push(1);return}const [u,v]=edges[i];for(let c=0;c<3;c++){if(deg[u]+c>nodes[u]||deg[v]+c>nodes[v])continue;deg[u]+=c;deg[v]+=c;cs.push(c);f(i+1,cs,deg);cs.pop();deg[u]-=c;deg[v]-=c}}f(0,[],Object.fromEntries(Object.keys(nodes).map(k=>[k,0])));assert(ans.length===1,"洲岛桥：唯一解")}

// Light Up、时间序、货运、对钻与 Nonogram 的固定完成状态均可穷尽验证。
{const N=6,walls=new Map([[28,2],[0,1],[33,1],[11,1],[5,0],[30,1],[13,0],[27,0],[16,1],[26,1],[17,0],[19,1],[7,1],[24,0]]),free=[...Array(36).keys()].filter(i=>!walls.has(i)),at=(r,c)=>r*N+c,inside=(r,c)=>r>=0&&r<N&&c>=0&&c<N,ix=Object.fromEntries(free.map((p,i)=>[p,i])),pop=x=>{x=x>>>0;x=x-((x>>>1)&0x55555555);x=(x&0x33333333)+((x>>>2)&0x33333333);return(((x+(x>>>4))&0x0f0f0f0f)*0x01010101>>>24)},cover=[],conflict=[];for(const p of free){const r=~~(p/N),c=p%N;let coverMask=1<<ix[p],clashMask=0;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]])for(let y=r+dr,x=c+dc;inside(y,x);y+=dr,x+=dc){const q=at(y,x);if(walls.has(q))break;coverMask|=1<<ix[q];clashMask|=1<<ix[q]}cover.push(coverMask);conflict.push(clashMask);}const clues=[...walls].map(([p,v])=>{const r=~~(p/N),c=p%N;let mask=0;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const y=r+dr,x=c+dc;if(inside(y,x)&&!walls.has(at(y,x)))mask|=1<<ix[at(y,x)];}return[mask,v];}),full=(1<<free.length)-1;let answers=0;outer:for(let state=0;state<=full;state++){for(let i=0;i<free.length;i++)if(state>>i&1&&state&conflict[i])continue outer;for(const[mask,value]of clues)if(pop(state&mask)!==value)continue outer;let lit=0;for(let i=0;i<free.length;i++)if(state>>i&1)lit|=cover[i];if(lit===full&&++answers>1)break;}assert(answers===1,"制玉灯阵：唯一解")}
{const p=['rice','timber','sand','jade','seed','pot','tools','reed'],w=[3,3,2,2,1,1,1,1],cap=[7,3,4];let n=0;function f(i,a){if(i===8){const load=[0,0,0];a.forEach((b,j)=>load[b]+=w[j]);if(load.some((v,j)=>v>cap[j]))return;const q=id=>a[p.indexOf(id)];if(q('rice')===0&&q('timber')===0&&q('sand')===1&&q('tools')===1&&q('jade')===2&&q('reed')===2&&q('seed')===2&&q('seed')!==q('pot'))n++;return}for(let b=0;b<3;b++)f(i+1,[...a,b])}f(0,[]);assert(n===1,"三舟货运：唯一解")}
{const p=['rice','timber','rope','sand','tools','pot','reed','jade','seed','shell','fish','basket'],w=[3,3,1,2,1,1,1,2,1,1,2,1],cap=[7,5,4,3];let n=0;function f(i,a){if(i===p.length){const load=[0,0,0,0];a.forEach((b,j)=>load[b]+=w[j]);if(load.some((v,j)=>v>cap[j]))return;const q=id=>a[p.indexOf(id)];if(q('rice')===0&&q('timber')===0&&q('rope')===0&&q('sand')===1&&q('tools')===1&&q('pot')===1&&q('reed')===1&&q('jade')===2&&q('seed')===2&&q('shell')===2&&q('fish')===3&&q('basket')===3)n++;return}for(let b=0;b<4;b++)f(i+1,[...a,b])}f(0,[]);assert(n===1,"四水道货运：唯一解")}
{const jobs=['west','east','thresh','winnow','dry','pack','ferry','store'];let n=0;function f(a){if(a.length===8){const p=Object.fromEntries(a.map((v,i)=>[v,i])),ok=p.west<p.east&&p.east<p.thresh&&p.winnow===p.thresh+1&&p.dry===p.east+3&&p.pack>p.dry&&p.ferry===p.pack+1&&p.store===7;if(ok)n++;return}jobs.filter(x=>!a.includes(x)).forEach(x=>f([...a,x]))}f([]);assert(n===1,"雨前八刻：唯一解")}
{const target=[[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[1,1,1,1,1,1,1],[1,1,1,0,1,1,1],[1,1,1,1,1,1,1],[0,1,1,1,1,1,0],[0,0,1,1,1,0,0]],row=['3','5','7','3·3','7','5','3'],col=['3','5','7','3·3','7','5','3'],runs=a=>a.join('').split('0').filter(Boolean).map(x=>x.length).join('·'),options=row.map(r=>[...Array(128).keys()].map(m=>[0,1,2,3,4,5,6].map(i=>(m>>i)&1)).filter(a=>runs(a)===r));let n=0;function f(y,g){if(n>1)return;if(y===7){if([0,1,2,3,4,5,6].every(x=>runs(g.map(r=>r[x]))===col[x]))n++;return}options[y].forEach(r=>f(y+1,[...g,r]))}f(0,[]);assert(n===1&&target.length===7,"夯土 Nonogram：唯一解")}
{const target=[[1,1,1,1,1,0,1,1,0,1],[0,0,1,1,1,1,1,0,0,0],[1,1,0,1,1,1,0,0,0,1],[0,0,0,1,0,0,0,0,0,0],[0,1,0,0,1,1,0,1,1,1],[0,1,0,1,1,1,0,1,1,1],[0,1,1,0,1,1,0,0,0,0],[1,1,1,1,0,1,0,1,1,1],[1,0,1,1,1,0,0,0,1,1],[1,0,1,1,1,0,1,1,1,1]],row=['5·2·1','5','2·3·1','1','1·2·3','1·3·3','2·2','4·1·3','1·3·2','1·3·4'],col=['1·1·3','1·1·4','2·4','4·1·3','3·3·2','2·4','2·1','1·2·1·1','2·3','1·1·2·3'],runs=a=>a.join('').split('0').filter(Boolean).map(x=>x.length).join('·'),options=row.map(r=>[...Array(1024).keys()].map(m=>[0,1,2,3,4,5,6,7,8,9].map(i=>(m>>i)&1)).filter(a=>runs(a)===r));let n=0;function f(y,g){if(n>1)return;if(y===10){if([0,1,2,3,4,5,6,7,8,9].every(x=>runs(g.map(r=>r[x]))===col[x]))n++;return}options[y].forEach(r=>f(y+1,[...g,r]))}f(0,[]);assert(n===1&&target.length===10,"夯土 10×10 Nonogram：唯一解")}
{const start=[1,4,8,7,3,5,6,2],inv=start.reduce((n,v,i)=>n+start.slice(i+1).filter(x=>x<v).length,0);assert(inv%2===0,"神徽九宫：滑动局面可复原")}
// 一潮四舟：四船等载重，唯一性来自水道能力、同舟与避让关系，而非容量排序。
{const ids=['fish','reed','lacquer','jade','sand','tools','timber','rope','shell','rice','seed','basket','pot'],weight=[2,1,2,2,2,1,3,1,1,2,1,1,1],load=[0,0,0,0];let answers=0;function f(i,a){if(answers>1)return;if(i===ids.length){if(load.some(v=>v!==5))return;const at=id=>a[ids.indexOf(id)],same=(...group)=>group.every(id=>at(id)===at(group[0]));const ok=at('fish')===0&&same('fish','reed')&&at('lacquer')!==at('rice')&&at('jade')===1&&same('jade','sand','tools')&&at('timber')===2&&same('timber','rope')&&at('shell')!==at('sand')&&same('rice','seed','basket')&&at('pot')===3;if(ok)answers++;return}for(let boat=0;boat<4;boat++){if(load[boat]+weight[i]>5)continue;load[boat]+=weight[i];f(i+1,[...a,boat]);load[boat]-=weight[i];}}f(0,[]);assert(answers===1,"一潮四舟：关系约束唯一解")}
// 三芯校孔：已验证的推钻序列能把三枚钻芯送入全部孔位。
{const rows=['#######','#  .  #','#  $  #','# $$# #','# . @ #','#   . #','#######'],w=7,wall=new Set(),targets=new Set();let player=0,stones=[];rows.forEach((row,y)=>[...row].forEach((ch,x)=>{const i=y*w+x;if(ch==='#')wall.add(i);if(ch==='.')targets.add(i);if(ch==='$')stones.push(i);if(ch==='@')player=i;}));for(const step of '→↑↑←←↓↓←↓→↑←←↑↑→↓→↑'){const d={"↑":[0,-1],"↓":[0,1],"←":[-1,0],"→":[1,0]}[step],x=player%w+d[0],y=~~(player/w)+d[1],next=y*w+x,hit=stones.indexOf(next);if(hit>=0){const beyond=(y+d[1])*w+x+d[0];if(wall.has(beyond)||stones.includes(beyond))throw new Error('谜题验收失败：三芯校孔推钻序列失效');stones[hit]=beyond;}else if(wall.has(next))throw new Error('谜题验收失败：三芯校孔推钻序列撞墙');player=next;}assert(stones.every(i=>targets.has(i)),"三芯校孔：存在可完成的推钻序列")}
console.log('所有固定题面均存在且只存在一个完成状态。');
